[[header]]
	name = "Showcase"
	url = "/en/showcase"
	weight = 1
[[header]]
	name = "Packages"
	url = "/en/packages"
	weight = 2
[[header]]
	name = "Documentation"
	url = "https://openfisca.org/doc/"
	weight = 3
[[header]]
	name = "About"
	url = "/en/about"
	weight = 4

[[footer]]
	name = "Legal notice"
	url = "/en/legal-notice"
	weight = 1
[[footer]]
	name = "Cookies and opt-out"
	url = "/en/tracking"
	weight = 2
[[footer]]
	name = "Contact us"
	url = "mailto:contact@openfisca.org?Subject=openfisca.org"
	weight = 3
[[footer]]
	name = "Service status"
	url = "https://stats.uptimerobot.com/A6WQWi553"
	weight = 4
[[footer]]
	name = "Contribute to this page"
	url = "https://github.com/openfisca/openfisca.org/"
	weight = 5
	identifier = "contribute"
