[[header]]
	name = "Showcase"
	url = "/fr/showcase"
	weight = 1
[[header]]
	name = "Packages"
	url = "/fr/packages"
	weight = 2
[[header]]
	name = "Documentation"
	url = "https://openfisca.org/doc/"
	weight = 3
[[header]]
	name = "A propos"
	url = "/fr/a-propos"
	weight = 4

[[footer]]
	name = "Mentions légales"
	url = "/fr/mentions-legales"
	weight = 1
[[footer]]
	name = "Cookies et option de retrait"
	url = "/fr/statistiques-d-usages"
	weight = 2
[[footer]]
	name = "Contactez-nous"
	url = "mailto:contact@openfisca.org?Subject=openfisca.org"
	weight = 3
[[footer]]
	name = "État des services"
	url = "https://stats.uptimerobot.com/A6WQWi553"
	weight = 4
[[footer]]
	name = "Contribuer à cette page"
	url = "https://github.com/openfisca/openfisca.org/"
	weight = 5
	identifier = "contribute"
