homepage_featured:
  - les_meves_ajudes
  - leximpact_socio_fiscal
  - revenu_de_base
  - rapu_ture
showcase:
  author:
    types:
      icons:
        default: user
        individual: user
        collective: users
        ngo: globe
        research_center: graduation-ap
        business: factory
        local_government: building
        national_government: landmark
