documentation_url: https://openfisca.org/doc/
status_url: https://stats.uptimerobot.com/A6WQWi553
contact_email: contact@openfisca.org
homepage_featured:
  - mes_aides
  - les_meves_ajudes
  - leximpact
  - revenu_de_base
  - rapu_ture
  - nsw_legislation_explorer
