baseURL = "https://openfisca.org/"
title = "OpenFisca"
theme = "OpenFisca-2022"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[params]
	documentation_url = "https://openfisca.org/doc/"
	status_url = "https://stats.uptimerobot.com/A6WQWi553"
	contact_email = "contact@openfisca.org"
	homepage_featured = [
		"mes_aides",
		"les_meves_ajudes",
		"leximpact",
		"revenu_de_base",
		"rapu_ture",
		"nsw_legislation_explorer"
	]

[languages]

	[languages.en]
		weight = 0
		languageName = "English"

		[languages.en.menu]

			[[languages.en.menu.header]]
				name = "Showcase"
				url = "/en/showcase"
				weight = 1
			[[languages.en.menu.header]]
				name = "Packages"
				url = "/en/packages"
				weight = 2
			[[languages.en.menu.header]]
				name = "Documentation"
				url = "https://openfisca.org/doc/"
				weight = 3
			[[languages.en.menu.header]]
				name = "About"
				url = "/en/about"
				weight = 4

			[[languages.en.menu.footer]]
				name = "Legal notice"
				url = "/en/legal-notice"
				weight = 1
			[[languages.en.menu.footer]]
				name = "Cookies and opt-out"
				url = "/en/tracking"
				weight = 2
			[[languages.en.menu.footer]]
				name = "Contact us"
				url = "mailto:contact@openfisca.org?Subject=openfisca.org"
				weight = 3
			[[languages.en.menu.footer]]
				name = "Service status"
				url = "https://stats.uptimerobot.com/A6WQWi553"
				weight = 4
			[[languages.en.menu.footer]]
				name = "Contribute to this page"
				url = "https://github.com/openfisca/openfisca.org/"
				weight = 5
				identifier = "contribute"

	[languages.fr]
		weight = 1
		languageName = "Français"

		[languages.fr.menu]

			[[languages.fr.menu.header]]
				name = "Showcase"
				url = "/fr/showcase"
				weight = 1
			[[languages.fr.menu.header]]
				name = "Packages"
				url = "/fr/packages"
				weight = 2
			[[languages.fr.menu.header]]
				name = "Documentation"
				url = "https://openfisca.org/doc/"
				weight = 3
			[[languages.fr.menu.header]]
				name = "A propos"
				url = "/fr/a-propos"
				weight = 4

			[[languages.fr.menu.footer]]
				name = "Mentions légales"
				url = "/fr/mentions-legales"
				weight = 1
			[[languages.fr.menu.footer]]
				name = "Cookies et option de retrait"
				url = "/fr/statistiques-d-usages"
				weight = 2
			[[languages.fr.menu.footer]]
				name = "Contactez-nous"
				url = "mailto:contact@openfisca.org?Subject=openfisca.org"
				weight = 3
			[[languages.fr.menu.footer]]
				name = "État des services"
				url = "https://stats.uptimerobot.com/A6WQWi553"
				weight = 4
			[[languages.fr.menu.footer]]
				name = "Contribuer à cette page"
				url = "https://github.com/openfisca/openfisca.org/"
				weight = 5
				identifier = "contribute"

[module]
  [[module.mounts]]
    source = "./node_modules/lucide/dist/esm"
    target = "assets/js/lucide"

[markup.goldmark.renderer]
	hardWraps = true # Render newlines as <br>
	unsafe = true # Render raw HTML
