baseURL = "https://openfisca.org/"
title = "OpenFisca"
theme = "ananke"  # alternatives: https://themes.gohugo.io/github-project-landing-page/ https://themes.gohugo.io/hugo-universal-theme/

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[params]
	documentation_url = "https://openfisca.org/doc/"
	status_url = "https://stats.uptimerobot.com/A6WQWi553"
	contact_email = "contact@openfisca.org"

[languages]

	[languages.en]
		weight = 0
		languageName = "English"

	[languages.fr]
		weight = 1
		languageName = "Français"
