baseURL = "https://openfisca.org/"
title = "OpenFisca"
theme = "ananke"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true


[languages]
[languages.en]
weight = 0

[languages.fr]
weight = 1
