baseURL = "https://openfisca.org/"
theme = "ananke"
title = "OpenFisca"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true


[languages]
[languages.en]
weight = 0

[languages.fr]
weight = 1
