baseURL = "https://openfisca.org/"
title = "OpenFisca"
theme = "ananke"  # alternatives: https://themes.gohugo.io/github-project-landing-page/ https://themes.gohugo.io/hugo-universal-theme/

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]

[languages.en]
weight = 0
index = "Homepage"
countries = "Available countries"
analytics = "Analytics policy"
contribute = "Contribute to this page"
contact = "Contact us"
legal_notice = "Legal notice"


[languages.fr]
weight = 1
index = "Page d'accueil"
countries = "Pays disponibles"
analytics = "Analyses d'usage"
contribute = "Contribuer à cette page"
contact = "Contact"
legal_notice = "Mentions légales"
