baseURL = "http://openfisca.org/"
title = "OpenFisca"
theme = "ananke"  # alternatives: https://themes.gohugo.io/github-project-landing-page/ https://themes.gohugo.io/hugo-universal-theme/

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]

[languages.en]
weight = 0
languageName = "English"
index = "Homepage"

[languages.fr]
weight = 1
languageName = "Français"
index = "Page d'accueil"
