# CircleCI 2.0 configuration file. See <https://circleci.com/docs/2.0/language-python/>.
version: 2
jobs:
  build:
    parallelism: 4
    docker:
      - image: circleci/node:8-jessie-browsers
    environment:
      WATAI_TESTS: tests/integration
      SAUCE_USERNAME: openfisca
      # SAUCE_ACCESS_KEY is defined in the CircleCI web UI
      PORT: 1313 # openfisca.org & Hugo framework

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: sc-4.4.9
      - run:
          name: Install app dependencies
          command: npm install
      - run:
          name: Install saucelabs
          command: |
            npm install saucelabs  # allow sending Watai results to SauceLabs
            if [ -d sc ]; then exit; fi  # sc has already been downloaded
            mkdir sc
            wget https://saucelabs.com/downloads/sc-4.4.9-linux.tar.gz --directory-prefix sc
            tar -xzf sc/sc-4.4.9-linux.tar.gz --directory sc
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - save_cache:
          key: sc-4.4.9
          paths:
            - sc
      - run:
          name: Run app
          command: hugo serve
          background: true
      - run:
          name: Start Sauce Connect
          command: cd sc/sc-*-linux && ./bin/sc --user $SAUCE_USERNAME --api-key $SAUCE_ACCESS_KEY --tunnel-identifier "circle-$CIRCLE_BUILD_NUM-$CIRCLE_NODE_INDEX" --readyfile ~/sauce_is_ready > /tmp/sauce_log.txt
          background: true
      - run:
          name: Wait for Sauce Connect
          command: while [ ! -e ~/sauce_is_ready ]; do sleep 1; done
      - run:
          name: Wait for app to start
          command: wget --retry-connrefused --waitretry=1 --quiet http://localhost:$PORT
      - run:
          name: Prepare CI-specific config holder and add CI-specific config to Watai
          command: mkdir $HOME/.watai && cp $WATAI_TESTS/config-ci.js $HOME/.watai/config.js
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Kill Sauce Connect
          command: pkill sc
      - store_artifacts:
          path: /tmp/sauce_log.txt
          destination: sauce-log
  deploy:
      - run:
          name: Build app
          command: hugo
      - run:
          name: Publish openfisca.org
          command: npm run publish
      - run:
          name: Publish openfisca.org/doc
          command: ./publish-doc.sh
workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
