version: 2.1

orbs:
  hugo: circleci/hugo@0.3.1

jobs:
  test:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: npm test

  deploy:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - attach_workspace:
          at: .
      - run:
          name: Publish openfisca.org
          command: |
            touch public/.nojekyll # Bypass Jekyll processing on GitHub Pages
            npm run publish
      - run:
          name: Publish openfisca.org/doc
          command: ./publish-doc.sh

workflows:
  version: 2
  main:
    jobs:
      - test
      - hugo/build:
          version: '0.37'
          html-proofer: true
      - deploy:
          requires:
            - test
            - hugo/build
