version: 2.1

orbs:
  hugo: circleci/hugo@1.3.0

jobs:
  test:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: npm test

  html_validate:
    docker:
      - image: cimg/ruby:3.1.2-browsers
    steps:
      - checkout
      - run:
          name: Install html-proofer
          command: gem install html-proofer
      - attach_workspace:
          at: .
      - run:
          name: Check HTML common mistakes
          command: exec htmlproofer ./public --assume-extension .html --check-sri --disable-external --ignore-empty-alt

  deploy:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - attach_workspace:
          at: .
      - run:
          name: Publish openfisca.org
          command: |
            touch public/.nojekyll # Bypass Jekyll processing on GitHub Pages
            npm run publish
      - run:
          name: Publish openfisca.org/doc
          command: ./publish-doc.sh

workflows:
  version: 2
  main:
    jobs:
      - test
      - hugo/build:
          version: '0.106'
          html-proofer: false
      - html_validate:
          requires:
            - hugo/build
      - deploy:
          requires:
            - test
            - hugo/build
            - html_validate
          filters:
            branches:
              only: master
