name = "OpenFisca 2022"
license = "MIT"
licenselink = "https://github.com/openfisca/openfisca.org/themes/OpenFisca-2022//blob/master/LICENSE"
description = "The most widely adopted free and open-source engine to write rules as code"
homepage = "https://openfisca.org"
min_version = "0.101.0"
